<a href="https://colab.research.google.com/github/Yashb404/MUJ-ML-Lab/blob/main/ML_Lab_2_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Create array from Python list
lst = [10, 20, 30, 40, 50]
arr = np.array(lst)

print("Array:", arr)
print("Shape:", arr.shape)
print("Data Type:", arr.dtype)

Array: [10 20 30 40 50]
Shape: (5,)
Data Type: int64


In [2]:
import numpy as np

zeros_matrix = np.zeros((3,4))
ones_matrix = np.ones((2,5))

print("3x4 Zeros Matrix:\n", zeros_matrix)
print("Shape:", zeros_matrix.shape)

print("\n2x5 Ones Matrix:\n", ones_matrix)
print("Shape:", ones_matrix.shape)

3x4 Zeros Matrix:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape: (3, 4)

2x5 Ones Matrix:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Shape: (2, 5)


In [3]:
import numpy as np

arr = np.arange(1,13)

print("Original Array:", arr)
print("Original Shape:", arr.shape)

reshaped = arr.reshape(3,4)

print("\nReshaped Array:\n", reshaped)
print("Reshaped Shape:", reshaped.shape)

Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Original Shape: (12,)

Reshaped Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped Shape: (3, 4)


In [4]:
import numpy as np

arr = np.random.randint(1,100,10)

print("Array:", arr)

print("Minimum:", arr.min())
print("Maximum:", arr.max())
print("Mean:", arr.mean())
print("Sum:", arr.sum())

Array: [ 1  6 80 54 76 90 28 60 27 89]
Minimum: 1
Maximum: 90
Mean: 51.1
Sum: 511


In [5]:
import pandas as pd

data = {
    "Name": ["Aman", "Riya", "Karan", "Sneha"],
    "Marks": [85, 90, 78, 92]
}

df = pd.DataFrame(data)

print("DataFrame:\n", df)

print("\nData Types:")
print(df.dtypes)

DataFrame:
     Name  Marks
0   Aman     85
1   Riya     90
2  Karan     78
3  Sneha     92

Data Types:
Name       str
Marks    int64
dtype: object


In [10]:
import pandas as pd

df = pd.read_csv("../datasets/DATA  (1).csv")

print("First 5 rows:")
print(df.head())

print("\nLast 5 rows:")
print(df.tail())

First 5 rows:
  STUDENT ID\t1\t2\t3\t4\t5\t6\t7\t8\t9\t10\t11\t12\t13\t14\t15\t16\t17\t18\t19\t20\t21\t22\t23\t24\t25\t26\t27\t28\t29\t30\tCOURSE ID\tGRADE
0  STUDENT1\t2\t2\t3\t3\t1\t2\t2\t1\t1\t1\t1\t2\t...                                                                                         
1  STUDENT2\t2\t2\t3\t3\t1\t2\t2\t1\t1\t1\t2\t3\t...                                                                                         
2  STUDENT3\t2\t2\t2\t3\t2\t2\t2\t2\t4\t2\t2\t2\t...                                                                                         
3  STUDENT4\t1\t1\t1\t3\t1\t2\t1\t2\t1\t2\t1\t2\t...                                                                                         
4  STUDENT5\t2\t2\t1\t3\t2\t2\t1\t3\t1\t4\t3\t3\t...                                                                                         

Last 5 rows:
    STUDENT ID\t1\t2\t3\t4\t5\t6\t7\t8\t9\t10\t11\t12\t13\t14\t15\t16\t17\t18\t19\t20\t21\t22\t23\t24\t25\t26\t27\t28\t2

In [12]:
import pandas as pd

df = pd.read_csv("../datasets/DATA  (1).csv")

print("Dataset Info:")
print(df.info())

print("\nRows:", df.shape[0])
print("Columns:", df.shape[1])

print("\nMissing Values:")
print(df.isnull().sum())

Dataset Info:
<class 'pandas.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 1 columns):
 #   Column                                                                                                       Non-Null Count  Dtype
---  ------                                                                                                       --------------  -----
 0   STUDENT ID	1	2	3	4	5	6	7	8	9	10	11	12	13	14	15	16	17	18	19	20	21	22	23	24	25	26	27	28	29	30	COURSE ID	GRADE  145 non-null    str  
dtypes: str(1)
memory usage: 1.3 KB
None

Rows: 145
Columns: 1

Missing Values:
STUDENT ID\t1\t2\t3\t4\t5\t6\t7\t8\t9\t10\t11\t12\t13\t14\t15\t16\t17\t18\t19\t20\t21\t22\t23\t24\t25\t26\t27\t28\t29\t30\tCOURSE ID\tGRADE    0
dtype: int64
